### ISSUE TITLE
[BUG] Testing under 10.0 Dragonflight - Jostle module needs a lot of work

### ISSUE THREAD

**Issue by mightykong** [Kiatra/ChocolateBar#18]
Due to the amount of UI work Blizzard is doing with 10.0, I've been testing mods on Dragonflight.  

Jostle.lua is causing the most problems with Dragonflight, mostly when calling back to the Blizzard frames.  I'm assuming some of the frame names are changing and or the way of hooking them is changing.  This module will need a bit of work for 10.0  I'll submit error reports once I gather them.

**Comment by mightykong** [comment]
Line 112:  Hooksecurefunc() - Playerframe_SequencedFinished is not a function
Line 71: Attempt to call field ? a nil value - seems to be called during Jostle:Refresh()
Line 56: Attempt to call method Refresh a nil value

**Comment by jgwallace3** [comment]
Getting these also now that 10.0 is out

**Comment by gOOvER** [comment]
> Getting these also now that 10.0 is out

because its not updated for 10.0 ;)

**Comment by jgwallace3** [comment]
> > Getting these also now that 10.0 is out
> 
> because its not updated for 10.0 ;)

Of course! But there was a months advance notice due to mightykong's post and I was confirming I saw that on live now.

**Comment by Zwixx** [comment]
Opened #22. This fix all my Problems with the Patch

**Comment by Kiatra** [comment]
Since v3.9.6 you will need to use edit mode to move frames below the top bar. As there are still issues with the updates of the positions of the Minimap and Playerframes that are not fixed. So v3.9.6 will not try to move those frames.
