### ISSUE TITLE
Dragonflight pre-patch - Can't drag modules

### ISSUE THREAD

**Issue by fraerie** [Kiatra/ChocolateBar#19]
Can't drag to reorder modules

Have applied the jostle fix in other issue.

When trying to move a plug in - the texture for the 'drag icon onto button to select action' window stays until you do a reload.

**Comment by fraerie** [comment]
Getting this error today - I think it's related to the same issue

16x bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/ChocolateBar/Core.lua"]:586: in function <Interface/AddOns/ChocolateBar/Core.lua:580>
[string "@Interface/AddOns/ChocolateBar/Core.lua"]:593: in function `GetPointer'
[string "@Interface/AddOns/ChocolateBar/Bar.lua"]:390: in function `Drag'
[string "@Interface/AddOns/ChocolateBar/DragAndDrop.lua"]:74: in function `Start'
[string "@Interface/AddOns/ChocolateBar/Chocolate.lua"]:343: in function <Interface/AddOns/ChocolateBar/Chocolate.lua:316>

Locals:
(*temporary) = "bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))"

**Comment by Zwixx** [comment]
Opened #22. This fix all my Problems with the Patch

**Comment by Kiatra** [comment]
Fixed with v3.9
