### ISSUE TITLE
Dragonflight - Cannot move items, cannot use bottom bar

### ISSUE THREAD

**Issue by aggietallboy** [Kiatra/ChocolateBar#20]
Howdy!
All my broker pieces seem to show up, and still mostly work in DF, but only on the top bar.
I normally use a bottom bar (I've tried deleting, readding, adding new), but I cannot place any items on the bottom bar.

I also cannot rearrange anything.

**Comment by Yanngo** [comment]
It is unclear what error you are encountering but some folks have posted a couple of solutions that made the addon work for me over at curseforge. https://www.curseforge.com/wow/addons/chocolatebar/issues/109
There are still errors but the addon is usable.
Or feel free to download, rename, and replace this file in your addon's folder. 
[Jostle.lua.txt](https://github.com/Kiatra/ChocolateBar/files/9881918/Jostle.lua.txt)

**Comment by aggietallboy** [comment]
The edit to jostle.lua did the trick to make plugins show up on the bottom bar once more, thank you!!
However, bit o' weirdness still.

I've done edit mode (former bartender user) and when I enable Chocolate bar, it pushes my chat window back up to approximately the center of the screen.

Still not able to move plugins, and I still get the window popup when trying, which does not go away until reload ui

**Comment by Yanngo** [comment]
![image](https://user-images.githubusercontent.com/17704069/198836753-103e25e1-cf7e-4293-9dab-22c12725b02c.png)
Try disabling Adjust Blizzard Frames. It stopped moving chat frames for me after /reload.

**Comment by Zwixx** [comment]
Opened #22. This fix all my Problems with the Patch

**Comment by Kiatra** [comment]
Fixed with v3.9
