### ISSUE TITLE
[Bug Report] Addon breaks UI Edit mode

### ISSUE THREAD

**Issue by anyuta1166** [Kiatra/ChocolateBar#25]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

When Chocolate Bar is enabled, it breaks the Edit mode.

### Steps to reproduce.

Enable Chocolate Bar.
Open Edit Mode.
Try to switch between Classic and Modern layouts.
See that frames (especially the player frame) are positioned incorrectly.

### Expected behavior.

Should correctly switch between layouts.

### Errors

```lua
No LUA errors.
```

**Comment by Kiatra** [comment]
Fixed in v3.9.6. Use edit mode to move frames below the top bar.
