### ISSUE TITLE
[Bug Report] The description on the CurseForge  has broken links

### ISSUE THREAD

**Issue by b-morgan** [Kiatra/ChocolateBar#27]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

The description on the CurseForge page (https://www.curseforge.com/wow/addons/chocolatebar) contains multiple links that are no longer valid.

### Steps to reproduce.

Open the page, click on the links.

### Expected behavior.

Links that point to existing pages.

### Errors

```lua
N/A
```

**Comment by Kiatra** [comment]
Fixed the links.
