### ISSUE TITLE
[Bug Report] Bar with free positioning not sticking to the bottom of the screen

### ISSUE THREAD

**Issue by Licen-it** [Kiatra/ChocolateBar#33]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

 I enabled the free positioning for a second bar and i tried to stick to the bottom of the screen, but i notices there is about 1 millimeter space that is letting me see the ground and while moving i get easily distracted as i see stuff moving down there.

here is a screenshot
<img width="160" alt="image" src="https://github.com/Kiatra/ChocolateBar/assets/35496522/441eb5c8-2072-4c76-8eec-db38d5a82815">

### Steps to reproduce.

- enable free positioning for one bar
- unlock it
- drag to the bottom of the screen

### Expected behavior.

no space should be visible between the bar and the bottom of the screen

### Errors

```lua
no errors
```

**Comment by Licen-it** [comment]
@Kiatra any idea if there is a workaround until a proper fix?

**Comment by Kiatra** [comment]
I could reproduce the problem at first but now that I:

1. quit WoW
2. deleted the saved variables of CB: World of Warcraft/_retail_/WTF/Account/<account name>/SavedVariables/ChocolateBar.lua
3. and logged back in

I can not reproduce it the problem seems fixed by that hmm.

**Comment by Licen-it** [comment]
It would be interesting to know which property is there making it fail...but i'll try that to see if it's getting fixed for me as well.

**Comment by Kiatra** [comment]
Ok I will close the issue until we run into the issue again then you can reopen it.

**Comment by Licen-it** [comment]
<img width="143" alt="image" src="https://github.com/user-attachments/assets/30c87c29-67e7-416f-ab08-998a9941d6be">
Ok i was finally able to check it out, there is still a 1px space between the bar and the bottom for some reason, but it's way less bothering than before.

Anyway i compared the old configuration file and the new one after deleting the old, and i found the issue was caused by these settings:

<img width="250" alt="image" src="https://github.com/user-attachments/assets/b6491caa-d4b6-4bfe-a3ca-533ff4934ed9">

which i now changed into this and it's working perfectly with the old config file

<img width="243" alt="image" src="https://github.com/user-attachments/assets/037bc81d-9476-4fdc-8583-7b039037deff">
