### ISSUE TITLE
How to access Broker_MicroMenu

### ISSUE THREAD

**Issue by KyrosKrane** [Kiatra/ChocolateBar#34]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

ChocolateBar includes the files for a component called MicroMenu at `Interface\AddOns\ChocolateBar\modules\MicroMenu`; this seems functionally identical to the standalone addon [Broker_MicroMenu](https://github.com/Kiatra/Broker_MicroMenu). However, these files don't appear to be referenced anywhere in the main addon code. None of the code outside that directory appears to read the files in that directory.

The only references to `MicroMenu` outside that directory appear to be in `Interface\AddOns\ChocolateBar\modules\CB_Lauchers.lua` (line 14) and `Interface\AddOns\ChocolateBar\modules\CB_Lauchers_LibQTip.lua` (line 12), both of which reference the standalone addon's path `"Interface\\AddOns\\Broker_MicroMenu\\media\\"`.  (Side note: those two files appear to be misspelled as "Lauchers" instead of "Launchers".) There is one additional reference in `Interface\AddOns\ChocolateBar\modules\CB_PlayedTime_Loc.lua` which instructs that localization be done through `http://www.wowace.com/addons/Broker_MicroMenu/localization/` (a dead URL).

Should this module be packaged with ChocolateBar? If so, what's the intended way to access it?

### Steps to reproduce.

Load ChocolateBar with no other addons enabled. Create a bar (if not already there). Attempt to load the Broker_MicroMenu module.

### Expected behavior.

The Broker_MicroMenu is accessible in game.

**Comment by Kiatra** [comment]
This will be added later. You can install the standalone version until then: https://github.com/Kiatra/Broker_MicroMenu
