### ISSUE TITLE
[Bug Report] Blizzard API 'GetAddOnMetadata is deprecated 

### ISSUE THREAD

**Issue by Myrroddin** [Kiatra/ChocolateBar#35]
### What game version did the bug occur in?

Vanilla Classic, Burning Crusade Classic, Wrath of the Lich King Classic, Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

`GetAddOnMetadata` was added to the depreciated list at the beginning of Dragonflight. It has been replaced by `C_AddOns.GetAddOnMetadata` for all game versions.

I found the depreciated API on line 12 of Options.lua although it may exist elsewhere.

### Steps to reproduce.

I have checked if the API `C_AddOns` exists in all WoW versions, and it does return information. Continuing to use the older `GetAddOnMetadata` will stop functioning during the pre-patch for The War Within.

### Expected behavior.

Replacing outdated APIs before they cease to work and cause further issues.

### Errors

```lua
No errors yet, but they will come unless the API is updated in ChocolateBar.
```

**Comment by Kiatra** [comment]
Fixed with v3.14
