### ISSUE TITLE
[Bug Report] pkgmeta has obsolete URLs that point to nowhere

### ISSUE THREAD

**Issue by Myrroddin** [Kiatra/ChocolateBar#36]
### What game version did the bug occur in?

Vanilla Classic, Burning Crusade Classic, Wrath of the Lich King Classic, Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Your [.pkgmeta](https://github.com/Kiatra/ChocolateBar/blob/master/.pkgmeta) is pointing to Wowace URLs which haven't existed in years. None of your libs are being pulled from the correct repos.

### Steps to reproduce.

Update your pkgmeta. Here is an example of the current URLs: [RepByZone's pkgmeta](https://github.com/Myrroddin/repbyzone/blob/master/.pkgmeta).

To reference LibDataBroker-1.1, the correct format is to **not use** `tools-used` which is obsolete. Instead, use `curse-slug`. You can safely remove the entire `tools-used` section of your pkgmeta.

```lua
  libs/LibDataBroker-1.1:
    url: https://github.com/tekkub/libdatabroker-1-1/
    curse-slug: libdatabroker-1-1
```

Because `tools-used` is obsolete, you can remove findglobals as well.

### Expected behavior.

Rather than bundling library versions from before Twitch, and later Amazon, bought Curseforge, bundle the current library versions from the correct repository URLs.

### Errors

```lua
Given that Blizzard is being more aggressive with embedded libs not being bundled correctly, your current system will fail inevitably, and it is better to fix your issues now.
```

**Comment by Kiatra** [comment]
Please create a pull request for the enhancements
