### ISSUE TITLE
[Bug Report] Your libs.xml is loading Ace3 out of order

### ISSUE THREAD

**Issue by Myrroddin** [Kiatra/ChocolateBar#37]
### What game version did the bug occur in?

Vanilla Classic, Burning Crusade Classic, Wrath of the Lich King Classic, Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

The Ace3 libs have a required load order, as seen in the [Ace3 toc](https://github.com/WoWUIDev/Ace3/blob/master/Ace3.toc) file.

### Steps to reproduce.

What ChocolateBar is currently doing is trying to load various Ace3 libs before their prerequisite Ace3 libs are loaded. This will not end well. Your [lbs.xml](https://github.com/Kiatra/ChocolateBar/blob/master/libs/libs.xml) needs to follow the Ace3 load order, with external libs like LSM, LibQTip, and AceGUI-3.0-SharedMediaWidgets loaded last.

### Expected behavior.

Fixing the libs.xml file to prevent "not found" or "X is nil" errors as Blizzard gets more stringent about correct procedures with addons.

### Errors

```lua
No errors yet, but they will happen.
```

**Comment by Myrroddin** [comment]
I found more potential errors in your ToC. `no-lib-strip` is deprecated and should not be used. LibDataBroker-1.1 should be listed in your libs.xml file.

**Comment by Myrroddin** [comment]
These lines in your ToC can be compressed.
```lua
## Interface: @toc-version-retail@
## Interface-Retail: @toc-version-retail@
## Interface-Classic: @toc-version-classic@
## Interface-BCC: @toc-version-bcc@
## Interface-Wrath: @toc-version-wrath@
```

They become `Interface: 11503, 40400, 110002`

**Comment by Kiatra** [comment]
Please create a pull request for the enhancements
