### ISSUE TITLE
[Bug Report] The Bar is not long displayed

### ISSUE THREAD

**Issue by grilor** [Kiatra/ChocolateBar#40]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

i have disabled ALL addon but this one and it is not showing up at all now. 

### Steps to reproduce.

loggin with allmy addons turned on and the bar was gone. removed all addons but this one and the bar is still gone

### Expected behavior.

for the bars to be displayed on the in-game screen

**Comment by Mekilya** [comment]
Same issue as well. Bar is no longer displayed

**Comment by Dranni21312** [comment]
The following changes made the addon work again for me:

MicroMenu\Broker_MicroMenu.lua:212: Change to `C_AddOns.LoadAddOn("Blizzard_TalentUI")`
Core.lua:9: Change to `C_AddOns.GetAddOnMetadata("ChocolateBar", "Version")`
Core.lua:281: Change to `return lastversion < C_AddOns.GetAddOnMetadata("ChocolateBar", "Version") and true or false`
Options.lua:12: Change to `local version = C_AddOns.GetAddOnMetadata("ChocolateBar","X-Curse-Packaged-Version") or ""`

**Comment by Mekilya** [comment]
unfortunately I am not very computer savvy so the add on changes are very confusing and I would not even begin to know where to fix these on my own

**Comment by Dranni21312** [comment]
Here's the latest version of the addon with the changes I referenced:

https://easyupload.io/bgs1lx 

Please delete if not allowed.

**Comment by Navanya80** [comment]
> Here's the latest version of the addon with the changes I referenced:
> 
> https://easyupload.io/bgs1lx
> 
> Please delete if not allowed.

Not sure if I did it wrong, but I downloaded this and unzipped it to my addon folder and still nothing, Chocolate bar still doesn't show up on my screen.

**Comment by ctrob67** [comment]
> Not sure if I did it wrong, but I downloaded this and unzipped it to my addon folder and still nothing, Chocolate bar still doesn't show up on my screen.

I just made the changes manually and I don't get errors but I don't get the bar either.

**Comment by Kiatra** [comment]
Fixed in v3.14
