### ISSUE TITLE
Durability percentage no longer show's up  

### ISSUE THREAD

**Issue by Mekilya** [Kiatra/ChocolateBar#42]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that ChocolateBar is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

For some reason once the add on was updated my Broker durability percentage no longer appears to be showing just the repair Icon. Not sure is its chocolate bar or actually broker durability 

### Steps to reproduce.

disabled and re-enabled

### Expected behavior.

Not sure if it actually Chocolate or Broker that's the issue

**Comment by Kiatra** [comment]
Broker_DurabilityInfo seems to work fine for me. what is the exact name of the Addon you use? :)

**Comment by Mekilya** [comment]
It is now working, Broker_Durability finally updated yesterday and I now
have the Durability % displayed like I always have..
Thank you for your hard work I really do love Chocolate Bar compared to
other Add ons
