### ISSUE TITLE
Mouse issue

### ISSUE THREAD

**Issue by monne55** [Kiatra/ChocolateBar#6]
I cant click and drag on top of my char in game.

It seems to be related to this frame (found with /fstack)
![fstack](https://user-images.githubusercontent.com/73218396/96685932-18559100-137e-11eb-9838-3ecefebb9033.png)

**Comment by monne55** [comment]
Apparently it is a conflict issue with elvui. Alone both addons are ok, but when both are loaded i get the issue

**Comment by Kiatra** [comment]
Could be an issue with one of the broker plugins? The one that makes the CB_Skin_OptionsFrame? Is that from elvui?
